version: '3.4'
services:

  hello-nginx-ci-web:
    image: "${APP_IMAGE_TAG}"
    ports:
      - "80:80"
    networks:
      - hello-nginx-ci-network
    command: ["nginx", "-g", "daemon off;"]

networks:
  hello-nginx-ci-network: {}